### PR TITLE
ci: add support for arm64

### LINKED ISSUE #129: Support multiarch image
Hello, it seems that `ryot` currently runs only on `am64`. Is there any plan to add support for `arm64` in the future ?

Thank you very much !

### PR DESCRIPTION
**Pull request by vnghia**
Close #129 

- Add multiarch image for docker
- Add arm64 build binary

### CODE REVIEW

**Comment by vnghia** [comment]
So there are two big changes here:
- We have to switch the compiler to `clang` because `ring` requires it: https://github.com/briansmith/ring/issues/1414.
- While switching to `clang`, `sqlite` does not compile with LFS (large file support) https://www.oreilly.com/library/view/using-sqlite/9781449394592/re46.html. In addition, `arm64` does not compile with thread-safe. So on `arm64`, only there will be only one connection to the database at any time.

Personally, I am using Postgresql so everything seems to be working normally on my server. The two images can be found here if you want to do further examination. https://github.com/vnghia/ryot/pkgs/container/ryot

**Comment by vnghia** [comment]
It seems that `sqlite` does not work on `arm64` at all because `sqlx` uses `connection pool` thus multithread. But `postgresql` is fine for me.

**Comment by vnghia** [comment]
Or we can build directly on `arm64` by using `qemu`. With this solution, we only need to disable LFS and `sqlite` is working well under `arm64`. However, the building time (with no cache) is 5 hours :/ https://github.com/vnghia/ryot/actions/runs/5258780249/jobs/9503470042

**Comment by IgnisDa** [comment]
5 hours? Won't that exceed GitHub free quota?

**Comment by vnghia** [comment]
I think the limit is 6 hours. If you feel this is too complicated, just close this PR and I will manage an arm64 image version in my repo.

**Comment by IgnisDa** [comment]
5hrs is too much. I'm fine with dropping sqlite support in arm64. Is it possible to have support for all databases normally and just 2 databases in arm64? Maybe the build script can be adapted to that.

**Comment by IgnisDa** [comment]
If someone needs sqlite support for arm64, they can always build it themselves.

**Comment by IgnisDa** [comment]
@vnghia Can you check if jobs work fine in your arm64 build since they use sqlite (in memory mode)? You can trigger a job from under the "Miscellaneous" tab in the settings page.

**Comment by vnghia** [comment]
I am doing some experiences on my side. I will get back to you soon (including the jobs)

**Comment by vnghia** [comment]
I observerd high CPU usage while using the `arm64` version that is cross-compiled on an `am64` host but it does not happen for the `arm64` image that is compiled by `qemu`. I am suspecting it has something to do with the `ring` library. Since we can not wait for 6 hours, I am suggesting that we make our build script `arm64` ready but only build `amd64` by default. And user can fork this and build themselve. Maybe set a variable in Github action setting and set the `platform` like `"arm64,amd64" if GITHUB_BUILD_ARM else "amd64"`

**Comment by IgnisDa** [comment]
Sounds good to me. Could you add those instructions in `docs/guides/platforms.md`?

**Comment by vnghia** [comment]
Finally, I successfully managed to make `sqlite` work with cross-compilation on `amd64` to `arm64` and also the . The trick here is to force `clang` to use `musl` include/lib instead of the default one. This reduces the CI time to approximately 30 minutes. See here https://github.com/vnghia/ryot/actions/runs/5305933666/jobs/9603214638 and here https://github.com/vnghia/ryot/pkgs/container/ryot/102574269?tag=v1.3.2

**Comment by IgnisDa** [comment]
LGTM!

**Pull request merged**
