### PR TITLE
Finished changes for dynamic UI sizing.

### LINKED ISSUE #655: Make better use of real estate with high res screens
The main content you are interacting with uses a quite small area when using a 4k screen. It makes it tricky keeping an overview and easily updating your progress. 

image

Regardless of which page you are on, it basically only ever uses a frame about the size of the red box. 

I would love to see ryot use more of available screen real estate. It would greatly improve usability and seems like a relatively easy fix to me.

### PR DESCRIPTION
**Pull request by MattMckenzy**
I went ahead and figured out a nice way to handle dynamic screen sizing / higher resolutions. Should fix #655.

I essentially changed Containers from a static size to a fluid style with some extra margins, changed the layout for ApplicationGrid from a SimpleGrid to a Flex with wrap and updated some max-heights to use view height instead of a static size. I feel like everything flows well now, but no worries if you want to make further changes!

### CODE REVIEW

**Comment by IgnisDa** [comment]
I am not really sure the new UI looks very good.

Too much data in one row:

image

Calendar view is messed up:
image
image

**Comment by IgnisDa** [comment]
Regardless, I am pushing some changes that would need to be done on the backend if this change goes through.

**Comment by IgnisDa** [comment]
@MattMckenzy You might want to look into [responsive styles](https://mantine.dev/styles/responsive) and adjust for only screens larger than `2xl`.

Also thank you very much for the contribution!

**Comment by MattMckenzy** [comment]
Admittedly, I wasn't familiar with Mantine until yesterday, but from my quick look it didn't seem to have default responsive style tags for larger than xl, maybe it was customizable and I hadn't noticed! 

In my past web UI development, I've always preferred to keep things as dynamic as possible vs hard coding it based on screen size, but I understand that could just be my preference.

If you feel the flex grid shows too many items, we could always increase the gap size as well!

**Comment by MattMckenzy** [comment]
Apologies, just added a commit that fixes the media item overview panel as well! I hadn't noticed it previously also using responsive styles with static sizing.

**Comment by IgnisDa** [comment]
Have you been able to get the project running locally? This is how the media details page looks with the latest changes.
image

**Comment by IgnisDa** [comment]
I think we should cap the width of the container to 1280px like GitHub does (instead of Mantine's default 960px). Otherwise things look a bit too stretched out.

image

**Comment by IgnisDa** [comment]
Closing in favor of #769.

**Pull request closed without merging**
