### PR TITLE
doc: add cosmos as install method

### LINKED ISSUE #290: Doc: Cosmos installer
We added a one click installer to Cosmos for Ryot, in case you want to mention it somewhere in the install process for example.
There's also a link that gives you the app on the market directly: https://cosmos-cloud.io/proxy#cosmos-ui/market-listing/cosmos-cloud/Ryot

image

Feel free to close this ticket if irrelevant!
Thanks!

image

### PR DESCRIPTION
**Pull request by azukaar**
Let me know if this is what you had in mind :)

Fixes #290.

### CODE REVIEW

**Comment by IgnisDa** [comment]
Will it be possible to embed the button in the mkdocs as you mentioned in https://github.com/IgnisDa/ryot/issues/290#issuecomment-1691609760?

**Comment by IgnisDa** [comment]
Thanks for your contribution!

**Comment by IgnisDa** [comment]
A small error on my part on the location of added docs. I pushed the fix in this commit https://github.com/IgnisDa/ryot/commit/c99f5fbfc0d8c89d68dbcff4e701e60994b0c70e.

**Comment by azukaar** [comment]
Thank you ! :)

**Pull request merged**
