### PR TITLE
ci: fix arm64 build

### PR DESCRIPTION
**Pull request by vnghia**
@IgnisDa could you test a docker build with this PR on Github Actions ? I will add an explaination later.

### CODE REVIEW

**Comment by IgnisDa** [comment]
I'll have to change the workflow to do that, and i am hesitant to do it. Does the latest docker image not work on your arm64 machine?

**Comment by vnghia** [comment]
## Running `arm64` image on `amd64` machine

You can test a `arm64` image on `amd64` if you have `qemu` set up correctly ([here](https://github.com/multiarch/qemu-user-static?tab=readme-ov-file#getting-started)) by running
```bash
docker run --rm --platform amd64 ghcr.io/ignisda/ryot:v6.9.4
docker run --rm --platform arm64 ghcr.io/ignisda/ryot:v6.9.4
```
The first command will show something like this which indicates that `ryot` was running.
```
[backend] 2024-08-01T07:14:45.136766Z  INFO ryot: Running version: v6.9.4
[backend] Error: Failed to validate config/ryot.yaml.
[backend]
[backend] Caused by:
[backend]     database.url: must not be empty
[backend]
[backend] BACKEND_PORT=5000 /usr/local/bin/ryot exited with code 1
```
The second command however will show this which indicates that `ryot` did not run at all.
```
[backend] /bin/sh: 1: /usr/local/bin/ryot: not found
[backend] BACKEND_PORT=5000 /usr/local/bin/ryot exited with code 127
```

## Cross compiling `arm64` from `amd64`

In our current setup, we are telling `cargo` to run on a `amd64` machine (host) and produce a binary that will work on `arm64` machine (target). To do that, you have to supply the `--target` option while invoking `cargo`.

If you remove that option, `cargo` will always build a binary for the host architecture (in this case is `amd64`) which will get coppied into the `arm64` Docker image and will not work.

## What is my PR doing ?

To compile with `openssl`, you must have a compiled shared library (`.so`) and the headers (`.h`) or you have to re-compile `openssl` from source.

If you go down the shared library, you have to install the correct `libssl-dev` version for the target architecture and point the compiler as well as pkg-config to the correct location. It is really cumbersome so I go the other way around. By enabling `vendored` features, the `openssl` will pull the source of `openssl`, compile it and statically link it to the final binary while invoking `cargo build`. The downside of this approach is now you have two copies of `openssl` (one in the rust binary and one is the shared library for nodejs)

## Some additional thoughts

I also went into rust development lately with an OpenSubsonic server. You could take a look at my ci [here](https://github.com/vnghia/nghe/actions/runs/10184033815). In that setup, I didn't use `cargo chef` because:
- I found it hard to setup `cargo chef` correctly, especially for cross-compiling.
- It requires docker but I want the ci to be as close as possible with local development, i.e calling `cargo build` should work everywhere.

So finally, I use `cargo build` and one specialized action for caching rust (it caches the `target` directory). For cross-compiling, I use https://github.com/cross-rs/cross. The ci run for every commit with the `debug` profile and it doesn't take too much time. The `release` profile takes much more time and will only be used for a release build.

I think enable the ci for every commit and switch the profile between `debug`/`release` will provide a more friendly development experiment for other contributors.

**Comment by IgnisDa** [comment]
THis is a good suggestion. I think we can get rid of cargo chef and set it up like your project (looks cool BTW!).

Will you be willing to make a PR?

**Comment by vnghia** [comment]
I will send a PR right away

**Comment by IgnisDa** [comment]
Thank you very much!

**Comment by vnghia** [comment]
@IgnisDa, could you test `ghcr.io/vnghia/ryot:test`. I am testing on my repo and the whole CI seems take only 9 minutes without caching. https://github.com/vnghia/ryot/actions/runs/10212510384?pr=6

**Comment by IgnisDa** [comment]
@vnghia It does not seem to be working on my machine (amd64) 
image

**Comment by vnghia** [comment]
@IgnisDa Please try again the latest build, using the same tag. You probably need to add `--pull always`

**Comment by IgnisDa** [comment]
Are you compiling in debug mode? 
image

This error should go away once it is compiled in release mode. Can you release one without the entire `if cfg!(debug_asseritons)`?

**Comment by IgnisDa** [comment]
One concern I have with your new approach (great job btw, very clever!) is that the node modules directory. Some node modules are written in c and they need to be compiled on the host system. Do you think this might cause problems?

**Comment by vnghia** [comment]
Tbh I don't think always building with release profile is a good idea because it takes more time (with caching it will be probably faster) and some debug information are stripped which makes it hard to debug.

About your concern, since we need the output template html, we can build the frontend twice, one directly on the host machine to get the html, and the latter one inside the docker to ensure that the modules written in c works correctly.

**Comment by IgnisDa** [comment]
Thrn can you push an image without the if block? The line number is jn the screenshot above

**Comment by IgnisDa** [comment]
Hey @vnghia, any updates on this?

**Pull request closed without merging**
