### PR TITLE
Fix missing "ps" terminal command on app crash/exit

### PR DESCRIPTION
**Pull request by dimon222**
Fixes errors with invocations of "ps" terminal command...
Current master/latest contains some code/libraries that invoke "ps" command under certain circumstances (perhaps specific architectures or such).

Example of error this meant to solve:
```
[backend] 2024-08-06T01:06:23.929688Z  INFO sea_orm_migration::migrator: Applying all pending migrations
[backend] 2024-08-06T01:06:23.935904Z  INFO sea_orm_migration::migrator: No pending migrations
[backend] thread 'main' panicked at apps/backend/src/main.rs:159:28:
[backend] called `Result::unwrap()` on an `Err` value: ParseError(())
[backend] BACKEND_PORT=5000 /usr/local/bin/ryot exited with code 101
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: spawn ps ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at onErrorNT (node:internal/child_process:484:16)
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 17 ]
}

Node.js v20.10.0
```

PS: it may not solve the problem of the core reason of why app itself crashed in my particular example, but it will allow app to handle shutdown gracefully in case of shutdown/crash flow.

### CODE REVIEW

**Comment by IgnisDa** [comment]
Can you tell me how to reproduce the issue? The particular error you are getting comes from concurrently killing the frontend if the backend dies. So that error is expected.

**Comment by dimon222** [comment]
> Can you tell me how to reproduce the issue? The particular error you are getting comes from concurrently killing the frontend if the backend dies. So that error is expected.

In my case I caused the state when app wasn't able to launch like specified TZ with typo. I suspect it would throw this error always for any state when backend doesn't start and based on error it invokes "ps" command but it doesn't exist (not installed). with ps installed the all does shutdown hook gracefully without this extra error.

**Comment by IgnisDa** [comment]
Makes sense. I will merge this once #939 is merged since that will introduce conflicts.

**Comment by IgnisDa** [comment]
Thanks for the contribution!

**Pull request merged**
