### PR TITLE
Fixed bug in is_metadata_finished_by_user

### PR DESCRIPTION
**Pull request by Jacob-Tate**
This function will mark unseen shows as finished since all episodes are marked 0 views which is == to the max of 0 shows

### CODE REVIEW

**Comment by IgnisDa** [comment]
Can you give me steps that I can use to reproduce the original issue on a fresh instance? I am not able to understand why these changes are needed.

**Comment by Jacob-Tate** [comment]
1．Navigate to show tab
image

2. Search any show
image

3. Add to any collection
image

4. Navigate to Misc tab and perform background tasks
5. Navigate back to show tab
image

**Comment by Jacob-Tate** [comment]
When attempting to check this occurs because you are checking for the highest episode seen count and the lowest which are both 0 therefore they == and are considered finished

**Comment by IgnisDa** [comment]
But the show is not finished since it has already been added to a collection. By that logic, why should this function return `true`?

**Comment by Jacob-Tate** [comment]
The original code returned true the new code will return false. When you have a show without any watch time it will say that it is finished.

**Comment by Jacob-Tate** [comment]
Copy of explanation from discord

If we modify the code with some useful debug statements:

```rust
    let values = bag.values().cloned().collect_vec();
    tracing::debug!("bag {:?}", bag);
    tracing::debug!("seen_history {:?}", seen_history);
    
    tracing::debug!("min {:?} max {:?}", values.iter().min(), values.iter().max());


    let is_complete = values.iter().min() == values.iter().max();
    is_complete
} else {
    seen_history.iter().any(|h| h.state == SeenState::Completed)
};
tracing::debug!("{:?} is {:?}", metadata.model.title, is_finished);
```

Then run this we will get
```
2024-07-30T23:51:28.385378Z DEBUG ryot::miscellaneous: bag {"3-7": 0, "4-6": 0, "1-2": 0, "1-9": 0, "3-2": 0, "2-4": 0, "2-7": 0, "4-5": 0, "2-10": 0, "3-6": 0, "4-8": 0, "1-6": 0, "1-7": 0, "4-9": 0, "4-10": 0, "2-1": 0, "2-3": 0, "2-2": 0, "4-1": 0, "4-3": 0, "2-6": 0, "1-3": 0, "2-5": 0, "3-3": 0, "1-5": 0, "3-5": 0, "3-8": 0, "4-4": 0, "1-4": 0, "3-10": 0, "4-7": 0, "3-4": 0, "4-2": 0, "1-8": 0, "3-1": 0, "2-8": 0, "1-10": 0, "3-9": 0, "1-1": 0, "2-9": 0}
2024-07-30T23:51:28.385502Z DEBUG ryot::miscellaneous: seen_history []
2024-07-30T23:51:28.385548Z DEBUG ryot::miscellaneous: min Some(0) max Some(0)
2024-07-30T23:51:28.385625Z DEBUG ryot::miscellaneous: "Snowpiercer" is true
```
With no views on any episodes
image

vs with the provided fix
```
2024-07-30T23:54:25.367310Z DEBUG ryot::miscellaneous: bag {"4-2": 0, "1-7": 0, "4-10": 0, "3-5": 0, "3-2": 0, "3-10": 0, "4-8": 0, "1-5": 0, "1-4": 0, "2-10": 0, "4-3": 0, "4-4": 0, "4-6": 0, "3-6": 0, "4-5": 0, "2-3": 0, "1-2": 0, "2-7": 0, "4-7": 0, "1-9": 0, "2-5": 0, "2-6": 0, "1-8": 0, "1-10": 0, "2-4": 0, "3-4": 0, "3-7": 0, "2-8": 0, "2-1": 0, "3-8": 0, "4-9": 0, "1-3": 0, "3-3": 0, "3-1": 0, "1-1": 0, "1-6": 0, "3-9": 0, "2-2": 0, "4-1": 0, "2-9": 0}
2024-07-30T23:54:25.367500Z DEBUG ryot::miscellaneous: seen_history []
2024-07-30T23:54:25.367569Z DEBUG ryot::miscellaneous: min Some(0) max Some(0)
2024-07-30T23:54:25.367706Z DEBUG ryot::miscellaneous: "Snowpiercer" is false
```

**Comment by IgnisDa** [comment]
Ah makes sense. Thanks!

**Pull request merged**
