### PR TITLE
fix Dockerfile for arm64 build

### PR DESCRIPTION
**Pull request by vnghia**
The reason is `node-base` should only be used for building. It uses `amd64` regardless the target architecture because running on `amd64` is faster and the output (`*.html`, `*.css`, `*.js`) is cross-platform compatible.

However if you use `node-base` to run something on `arm64`, it will throw `exec format error`. Before, we use `scratch` image so it is not an issue.

This PR use the correct base image for the final image and should fix running `ryot` on `arm64`.

### CODE REVIEW

**Comment by IgnisDa** [comment]
@vnghia Thanks for the PR. Did you make the changes you mentioned in https://github.com/IgnisDa/ryot/issues/540#issuecomment-1873135034 ? Honestly, I have no idea how docker platforms work so I am relying on your expertise here 😅.

**Comment by vnghia** [comment]
Not yet. I think it is better to do it in another PR so we can revert it if it is not the real reason.

**Comment by vnghia** [comment]
OR we can compile against normal `libc` with target (e.g `aarch64-unknown-linux-gnu`) and keep `node:slim`. Which one do you prefer ?

**Comment by IgnisDa** [comment]
From what little knowledge I have, `libc` is more performant right?

**Comment by vnghia** [comment]
Yes `libc` is more performant but have better community support (see https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-1-with-host-tools) but it is a little bit larger and somewhat harder to have a fully static build. `musl` is smaller, slower but can have a full static build which can be use with `scratch` image.

**Comment by IgnisDa** [comment]
The docker image is already over 800mb, so does scratch does not make sense anyway. I think we can go with libc?

**Comment by vnghia** [comment]
Yes I will send another PR. please merge this one !

**Comment by IgnisDa** [comment]
Should I make this a pre-release?

**Comment by vnghia** [comment]
I think you can, so people `arm64` can test it beforehand.

**Comment by IgnisDa** [comment]
@vnghia You made the PR from your main branch, so I can not push anything to that branch. Will it be possible to make the PR from a new branch?

**Pull request closed without merging**
