### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by IgnisDa**

### CODE REVIEW

**Comment by Ardakilic** [comment]
Heya, I believe something here or #494  broke the pipeline, tried to check but could not find the root cause https://github.com/IgnisDa/ryot/actions/runs/6920055816/job/18824125361#step:7:3295

**Comment by vnghia** [comment]
I will take a look

**Comment by IgnisDa** [comment]
Since your PR, I have removed support for SQLite and MySQL, so the workarounds you did back then might not be needed anymore.

**Comment by vnghia** [comment]
Oh that's great !

**Pull request merged**
