### PR TITLE
Emby integration

### LINKED ISSUE #187: [FEATURE REQUEST] - Emby Webhook Integration
It would be great if Ryot could accept webhooks from Emby. When a movie finishes in Emby, a webhook could be sent to Ryot to track the date the movie was listened to, minimizing manual input.

Reference: https://emby.media/support/articles/Webhooks.html

Similar to https://github.com/IgnisDa/ryot/issues/67

### PR DESCRIPTION
**Pull request by Jacob-Tate**
Moved over to this branch for emby integration related code.

Note from original PR #926

Added emby integration this could possibly be integrated into the jellyfin integration but there are a decent amount of differences so we should probably keep them separate.

I am planning to add emby as an import source as well but this should probably be done in the future in a separate PR.

Fixes #187.

### CODE REVIEW

**Comment by IgnisDa** [comment]
@Jacob-Tate Thanks! Can you check whether the changes I made work for you?

**Comment by Jacob-Tate** [comment]
confirmed its still working on my end

**Comment by Jacob-Tate** [comment]
didnt mean to close it

**Comment by IgnisDa** [comment]
LGTM, will merge this tomorrow.

**Comment by IgnisDa** [comment]
@Jacob-Tate I fOrgot about this. Can you add a small section about Emby in `integrations.md` as well?

**Comment by Jacob-Tate** [comment]
Added the integration documentation similar to the plex doc. Also fixed a grammar issue present in most of the integration boilerplate.

**Comment by IgnisDa** [comment]
THanks @Jacob-Tate!

**Pull request merged**
