### PR TITLE
docker: use concurrently instead of supervisord

### PR DESCRIPTION
**Pull request by vnghia**
/cc @IgnisDa

### CODE REVIEW

**Comment by IgnisDa** [comment]
Thanks! It seems you have removed the line which copies the caddy binary. I am not near my workstation rn, but will this image work without caddy?

**Comment by vnghia** [comment]
Seems to be a copy and paste error

**Comment by IgnisDa** [comment]
@vnghia Is it possible to use something other than NPM concurrently? I would rather not use npm in the final image. I took a look at https://github.com/jakswa/rouse but do you have other suggestions?

**Comment by vnghia** [comment]
This crate seems to be more updated: https://crates.io/crates/concurrently. But I think this is just a temporary workaround since we will split ryot into 2 images eventually

**Comment by IgnisDa** [comment]
I am fine with workarounds. I created an issue there too. https://github.com/tqwewe/concurrently/issues/7

**Pull request merged**
